### ISSUE TITLE
MapBuilder crash when load MH2O

### ISSUE THREAD

**Issue by oiramario** [namreeb/namigator#32]
MapBuilder crash when build data of Azeroth for WtoLK.
https://github.com/namreeb/namigator/blob/master/parser/Adt/Chunks/MH2O.cpp#L42
instance.Width and instance.Height are both zero.
It works fine for TBC because header.Mh2oOffset is always zero.

during researching I found the 0x14 offset cause this issue.
https://github.com/namreeb/namigator/blob/master/parser/Adt/Adt.cpp#L98
building success after remove this 0x14 offset.

what's your suggestion?

**Comment by namreeb** [comment]
I changed my mind.  I fixed this issue and left myself a note with https://github.com/namreeb/namigator/issues/33.
