### ISSUE TITLE
query_z wrong inside caves

### ISSUE THREAD

**Issue by namreeb** [namreeb/namigator#38]
Example 1: Map 0 ADT 50, 31 -9849.028, 134.545, 5.815 query_z returns a list of three identical values of 35.582
Example 2: Map 0, ADT 48, 32 -8617.701, -147.215, 87.239 query_z returns a list of three identical values of 145.589

**Comment by devw4r** [comment]
![image](https://user-images.githubusercontent.com/108442943/210159635-3243e150-76e6-406f-ac8b-54ae923993d7.png)
> Location - Map 0, X -8647.1396484375 Y -129.36000061035156
> Real Z 87.70490264892578
> Namigator query_z results:
> Namigator Z[0] 114.20716094970703
> Namigator Z[1] 114.20716094970703
> Namigator Z[2] 114.20716094970703
> Namigator Z[3] 114.20716094970703

![image](https://user-images.githubusercontent.com/108442943/210159653-21b3601a-08b0-46de-87c5-54a9b4fe63fa.png)
Location - Map 0, X -8590.5458984375 Y -143.14688110351562
Real Z 89.60712432861328
Namigator query_z results:
Namigator Z[0] 156.3370361328125
Namigator Z[1] 156.3370361328125
Namigator Z[2] 156.3370361328125

![image](https://user-images.githubusercontent.com/108442943/210159664-df66681b-13be-4780-8a09-29f45062d180.png)
Location - Map 0, X -9788.1455078125 Y 147.7585906982422
Real Z 25.114551544189453
Namigator query_z results:
Namigator Z[0] 58.94005584716797
Namigator Z[1] 58.94005584716797

![image](https://user-images.githubusercontent.com/108442943/210159740-7e546103-193f-45c8-88ec-abc868028cd6.png)
Location - Map 0, X -11125.2783203125 Y -117.76166534423828
Real Z 10.532085418701172
Namigator query_z results:
Namigator Z[0] 50.5771369934082
Namigator Z[1] 50.5771369934082
Namigator Z[2] 50.5771369934082

![image](https://user-images.githubusercontent.com/108442943/210159768-135b4947-5295-44cf-bbad-5729e71ebd9c.png)
Location - Map 0, X -13295.9755859375 Y -480.9395446777344
Real Z 17.734399795532227
Namigator query_z results:
Namigator Z[0] 77.89437103271484
Namigator Z[1] 77.89437103271484
Namigator Z[2] 77.89437103271484
Namigator Z[3] 77.89437103271484

**Comment by namreeb** [comment]
Can you try with commit https://github.com/namreeb/namigator/commit/496e0072d746faceabef6e03d4b796e95120dc93 and let me know if its fixed?  It seems to be for me.

**Comment by devw4r** [comment]
Finding some of the same issues:

![image](https://user-images.githubusercontent.com/108442943/220258502-e00937b7-db7d-45b9-ba46-5271f8600b26.png)

![image](https://user-images.githubusercontent.com/108442943/220258579-d06284c5-7d20-4ee7-8057-b7806530480f.png)

![image](https://user-images.githubusercontent.com/108442943/220259102-87929a72-16d7-4ca8-a332-d0efe0129e1d.png)


[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -113.66188118598966 Y -415.68063786502023
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -52.98414811817273 Y -404.6679182134722
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -99.05539023853669 Y -433.4828294287597
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -22.19026608605617 Y -372.92802430483823
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -85.83877585905162 Y -407.5936918675725
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -103.24486186286511 Y -422.2851826215904
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -117.50086350048163 Y -406.21428165144926
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -99.79032538194552 Y -435.4220108276871
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -59.987763106357264 Y -407.54760708826984
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -94.01510938494012 Y -397.6855763888393
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -120.92418182256282 Y -441.5841385397085
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -4.027497725276605 Y -373.58048995359695
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -98.8584310890257 Y -402.0632847026719
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -106.85908425630286 Y -426.70039757306773
[WARNING] [NAMIGATOR] Unable to find Z for Map 36 ADT [32,32] X -124.70499273772934 Y -439.12063135930964

**Comment by namreeb** [comment]
Haven't looked at map 36 yet, but the failures in the screenshots above should all be fixed by https://github.com/namreeb/namigator/commit/e66fe54ca9a71592f31e447730c2a9789efb63bd.

**Comment by namreeb** [comment]
Going to close this for now.  But please do let me know if there are any other places where query_z fails.
