### ISSUE TITLE
Make temporary obstacles and serializing of heightfield optional

### ISSUE THREAD

**Issue by namreeb** [namreeb/namigator#40]
This will save considerable RAM and disk space at the expense of having no support for temporary obstacles.

**Comment by killerwife** [comment]
Temporary obstacles are not a thing in wow for most operations. During the leak of 2.5.0 Enumerated strings, we learned blizz has this: "movement: Check for Doors when pathing (performance)"

Source: https://wow.tools/dbc/?dbc=enumeratedstring&build=2.5.1.38043#page=1 - check enum 1114

**Comment by namreeb** [comment]
Yeah.  When I wrote this code we didn't really know that.  Classic proved it definitively.

I'll still leave the capability in because I don't want to throw away so much work, but I'll probably leave generation turned off by default.

**Comment by namreeb** [comment]
Evidently I already did this.  https://github.com/namreeb/namigator/commit/2efd1cb524dc8d29d9843e22a713edd5b8146f99
