### ISSUE TITLE
Wrong WMO liquids parsing from alpha data

### ISSUE THREAD

**Issue by devw4r** [namreeb/namigator#46]
Stormwind.
![image](https://user-images.githubusercontent.com/108442943/233899120-c8af1f01-efb3-4006-be34-2ed572713b3b.png)

Undercity.
![image](https://user-images.githubusercontent.com/108442943/233899134-873827eb-c7c4-4f8f-9762-8c712f3dbcf0.png)

**Comment by namreeb** [comment]
Note to self: Azeroth (-8833, 628) for Stormwind.  I can't find an obvious explanation for this yet.

**Comment by namreeb** [comment]
Smaller WMOs from 0.5.3 and 1.12.1 that have MLIQ data, for comparison:

* `world\wmo\dungeon\az_deadmines\az_deadmines_a.wmo`
* `world\wmo\azeroth\buildings\stranglethorn_bootybay\bootybay.wmo`
* `world\wmo\azeroth\collidable doodads\elwynn\abbeygate\abbeygate01.wmo`

**Comment by namreeb** [comment]
Azeroth ADT (31, 48) has `world\wmo\azeroth\collidable doodads\elwynn\abbeygate\abbeygate01.wmo`

**Comment by namreeb** [comment]
1.12.1:
![image](https://github.com/namreeb/namigator/assets/5429489/15c3b3eb-b21a-4015-94f1-20e05e1b0d6d)

Alpha:
![image](https://github.com/namreeb/namigator/assets/5429489/fd5f701d-dcd1-4edc-8450-e32727e2b43a)

**Comment by namreeb** [comment]
For 1.12.1, the MLIQ chunk has a base vertex of `(-70.8333, 120.8333, -27.3881588)`.  For 0.5.3, the base vertex is `(-54.166, 120.833, -27.38815)`.  The difference here is probably what is setting this off.  Note that the y values are the same, and x is shifted to the left by 16.666, which matches visually the screenshots from the previous post.

**Comment by namreeb** [comment]
For reference: https://wowdev.wiki/WMO#MLIQ_chunk

For 0.5.3:
- Num verts = (5, 5)
- Width = 4
- Height = 4
- Base = (-54.1666641, 120.833328, -27.3881588)

For 1.12.1:
- Num verts = (5, 5)
- Width = 4
- Height = 4
- Base = (-70.8333282, 120.833328, -27.3881588)

When calculating the first vertex in

**Comment by namreeb** [comment]
Thanks to schlumpf pointing out that this is likely the result of mirroring.

**Comment by namreeb** [comment]
Should be fixed with https://github.com/namreeb/namigator/commit/bb4a2221cc1671cb059011710dd88c491925a81c
