### ISSUE TITLE
Unable to create BVHs for version 1.12

### ISSUE THREAD

**Issue by gtker** [namreeb/namigator#50]
As talked about on Discord, figured I would open an actual issue.

The 1.12 client does not have a `locale` directory or any MPQ files with it in the name, so it fails to find any data files.

[This is checked in the MpqManager here](https://github.com/namreeb/namigator/blob/a8a0b73a9772697153fd053ffb2d0e54e27ac171/parser/MpqManager.cpp#L121).

**Comment by namreeb** [comment]
This should be fixed by https://github.com/namreeb/namigator/commit/648c50b9c1f9edc6f32e703a380743dec0904342.
