### ISSUE TITLE
Add ability to detect if gameobjects/maps should be built

### ISSUE THREAD

**Issue by gtker** [namreeb/namigator#51]
Currently running the `mapbuild_build_bvh` and `mapbuild_build_map` functions don't test if the output files already exist.
It would be nice to have a (C API) way of testing whether it is necessary to build gameobjects/maps.

This could be either an external function in the C API or built into the current functions.

**Comment by namreeb** [comment]
The way this is intended to work is all BVHs are built as its own step (`./MapBuild --bvh`).  So I don't quite follow what you're asking for here.

**Comment by gtker** [comment]
I want, for example, a C function with a declaration of

```c
uint8_t game_objects_and_maps_built(char* directory);
```

That tells me (via 1 for true and 0 for false) whether the directory passed to the function contains "valid" namigator files, which means I don't have to build BVHs and Maps again, and can just read directly from the directory.

What exactly "valid" means in this context is undecided. Initially it could probably just check whether a `BVH` directory existed in the path, or if the directory contained some other file known to be from namigator.

I want this functionality in namigator itself and not manually implemented by me so that I'm not relying on implementation details that might suddenly change.

I don't see this as having to work together with https://github.com/namreeb/namigator/issues/49, since if I can control where the navigation files are stored I can also known whether they require a build/rebuild.
