### ISSUE TITLE
Building `Kalimdor` for 1.12 prints `Doodad not found`

### ISSUE THREAD

**Issue by gtker** [namreeb/namigator#59]
When building `Kalimdor` the following is output:
```text
Doodad world\wmo\outland\rubble\outlandrubble02.mdx not found
Doodad world\wmo\outland\rubble\outlandrubble01.mdx not found
Doodad world\wmo\outland\rubble\outlandrubble03.mdx not found
```

This used to be a `THROW_MSG` (commented out) but now it's just a `std::cerr` print.
Is this "supposed" to happen or is it a bug?

SHA256sums of MPQs:
```text
0bb2d6d370d825353eff5d9282c545a1b61980baaa5b7b65b1a7521e0ee8e27a  /home/asd/Downloads/Data112/backup.MPQ
f648e4fae190abcb25749ddbe96454e7e0de7e9c7e955983ed9d0e73b6986009  /home/asd/Downloads/Data112/base.MPQ
d9d5a290bdad848e177e2731c7ef221a1d7a6793e2c94e431488dd40816101e2  /home/asd/Downloads/Data112/dbc.MPQ
511189160f091eeb9d7ee8c473c1422b7f1fadbd9b65bfbf7d0a2a344103312d  /home/asd/Downloads/Data112/fonts.MPQ
6545dfbb3ef21a8b7f36b577419494cc292fec35585f9a1511d6c8b692b83191  /home/asd/Downloads/Data112/interface.MPQ
13aee674db39fc605c8aabf964eda0bb7895c6f026fed6c508bf2f9d155db0f9  /home/asd/Downloads/Data112/misc.MPQ
a7aa78c234bbdd450e00434e5939aa1a02383df1971cddcbfa181d68e9ab45a2  /home/asd/Downloads/Data112/model.MPQ
84f506c9f049f1e35f6d0f7b2e6643d28856888680ae2593436be8b9a058aad6  /home/asd/Downloads/Data112/patch-2.MPQ
a9ad25c9a32600dd3c71f97a0f95f9b9b629a9995988b928975c8871f1197683  /home/asd/Downloads/Data112/patch.MPQ
6ba131da952aae8d1e061b54468fd6e5d2ef78616540e2746ed21255d6b959a7  /home/asd/Downloads/Data112/sound.MPQ
a1564120452cd75c4c7b2002a668b12250a35dab658816a33b591ebb23004f52  /home/asd/Downloads/Data112/speech.MPQ
68fda6fb4f57051a47a0a56ff1757d73ee5c2a870774ba60ee8b52d7b36bc61d  /home/asd/Downloads/Data112/terrain.MPQ
7e5996d2a0a2de03c79dcf9ab78f3fce66264688eee56ca6dbc51c8ce4433dac  /home/asd/Downloads/Data112/texture.MPQ
9933d9ca23d481647880c9798dc7c225cd926f51026d148f09cd5251fc56edb7  /home/asd/Downloads/Data112/wmo.MPQ
```

**Comment by gtker** [comment]
> The "Doodad not found" error I think is due to bad data. I'm not sure that that doodad exists in any MPQs.

So this is just a "Blizzard messed up" error? If so, feel free to close this issue.

> As for why it's now std::cerr, I think that's because of a change made to make exceptions more compatible with Rust.
The `THROW` was commented out before I made the exception changes, I just also changed the comments to be in the new style for consistency.

**Comment by namreeb** [comment]
> So this is just a "Blizzard messed up" error? If so, feel free to close this issue.

I believe so, yes.  Either that, or there is an MPQ we should be loading, but aren't.  I did just encounter an example of this with 1.12.1 data yesterday, so it's certainly a possibility.  The easiest way to check would be to search all of the MPQs for that file, and see if it exists in any of them.

> > As for why it's now std::cerr, I think that's because of a change made to make exceptions more compatible with Rust.
> 
> The `THROW` was commented out before I made the exception changes, I just also changed the comments to be in the new style for consistency.

Oh, okay.  I'm guessing I used `std::cerr` because I don't consider it a fatal flaw, and processing should continue.

**Comment by gtker** [comment]
> Either that, or there is an MPQ we should be loading, but aren't.

Of the 1.12 MPQs, the following are not loaded:
```
backup.MPQ
fonts.MPQ
interface.MPQ
misc.MPQ
sound.MPQ
speech.MPQ
texture.MPQ
```

I'm not sure if any of them are supposed to be loaded, but several `speech-*.MPQ`s are loaded but the unnumbered `speech.MPQ` is not. Checking them with [Ladik's MPQ Editor](http://www.zezula.net/en/mpq/download.html) does not show the missing file in any of the MPQs.

Searching through all MPQs in merged mode I only find `World\Outland\PassiveDoodads\Rubble\outlandrubble01.m2` through `World\Outland\PassiveDoodads\Rubble\outlandrubble05.m2`. I'm not sure what relation the `.mdx` files have to `.m2` files.

I guess this is just a Blizzard error and the issue should be closed.

**Comment by namreeb** [comment]
In the MPQs they are called .m2, that part is corrected by my code.  Which MPQ had `World\Outland\PassiveDoodads\Rubble\outlandrubble01.m2`?

**Comment by namreeb** [comment]
Oh I just noticed the path is different.  Nevermind.  Yeah, I'm pretty sure that this is a Blizzard error.  If you find one that can't be found but IS in the MPQs, open a new issue with the specifics.
