### ISSUE TITLE
GlobalWMO Maps not working.

### ISSUE THREAD

**Issue by devw4r** [namreeb/namigator#70]
Even after being able to generate .map files for instances such as StormwindJail (No terrain) with #69, navigation does not work (query_z, find_heights, LoS, etc)

Also, those maps can't be opened using MapViewer. (Seems to be something related to serialization if no ADTs are present).

This seems also related to #63 (I noticed quadheight 120 as well).

I hope you can take a look at this soon @namreeb 

Thanks!

**Comment by namreeb** [comment]
Fixed with https://github.com/namreeb/namigator/commit/f03d9f172f448cc86fe0051f630d76dd86b6718f.
