### ISSUE TITLE
An error in compilation

### ISSUE THREAD

**Issue by qq987654321** [namreeb/namigator#79]
VS2022, when compiling "MapViewer", the header files "PixelShader. hpp" and "VertexShader. hpp" cannot be found.
May I ask how to configure it correctly.

![Uploading IM.png…]()

**Comment by namreeb** [comment]
I don't know what your problem might be.  But those files are produced by the VS shader tool.  Maybe you don't have it installed?  See here: https://github.com/namreeb/namigator/blob/master/MapViewer/CMakeLists.txt#L16-L28

**Comment by qq987654321** [comment]
Is VS shader tool？How to  installed it？I cant find it in Visual Studio Installer.I don't know much about this, can I be more detailed?

**Comment by namreeb** [comment]
Sorry, I don't really have time to provide technical support to Visual Studio.  But this might be a good place to start: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-part1.
